googleAnalytics = "G-L4M3E4SB0N"
baseurl = "https://trajectoryai.org/"
title = "Trajectory"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params]
    author = "TRAJECTORY"
    info = "AI Safety Workspace in Toronto, Canada"
    description = "Working to make the future a safer place for humans"
    keywords = "community"
    avatarurl = "/images/trajectoryai.png"

    favicon_32 = "favicon.ico"
    favicon_16 = "favicon.ico"


    hidecredits = true
    hidecopyright = true

    rtl = false
    math = true

# Social links
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope"
    weight = 2
    url = "https://mail.google.com/mail/u/0/?view=cm&fs=1&to=hello@trajectoryai.org&tf=1"
[[params.social]]
    name = "Slack"
    icon = "fab fa-slack"
    weight = 3
    url = "https://canada-ais.slack.com"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 3
    url = "https://github.com/trajectoryai"

